{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "uifactory.name" . }}
  labels:
    {{- include "uifactory.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- if .Values.ingress.wafPolicyId }}
    appgw.ingress.kubernetes.io/waf-policy-for-path: {{ .Values.ingress.wafPolicyId | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "uifactory.name" . }}-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "uifactory.name" . }}-{{ if .Values.frontend.enabled }}frontend{{ else }}api{{ end }}
                port:
                  number: 80
{{- end }}
